name = "PowerModelsDistributionStateEstimation"
uuid = "d0713e65-ce0c-4a8e-a1da-2ed737d217c5"
authors = ["Marta Vanin", "Tom Van Acker"]
version = "0.8.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[compat]
CSV = "0.10"
DataFrames = "1"
Distributions = "0.22.3 - 0.24.14, 0.25"
ForwardDiff = "~0.10.18"
InfrastructureModels = "~0.6, ~0.7"
JSON = "~0.18, ~0.19, ~0.20, ~0.21"
JuMP = "1.23.2"
LoggingExtras = "~0.4"
Optim = "~1.2.0, 1.7"
Polynomials = "~2.0.17, 3"
PowerModelsDistribution = "~0.11, ~0.12, ~0.13, ~0.14, ~0.15, ~0.16"
SpecialFunctions = "~1.5.1, ~1.6, ~1.7, ~1.8, ~2.0"
TestEnv = "1.102.0"
julia = "1.6 - 1.11"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSONTables = "b9914132-a727-11e9-1322-f18e41205b0b"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OpenDSSDirect = "a8b11937-1041-50f2-9818-136bb7a8fb06"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "Ipopt", "PowerModels", "HDF5"]
